#!/usr/bin/env python3

import hashlib, argparse, datetime, sys, configparser, os.path


def main():
    with open(os.path.expanduser('~/.secrets/dharmacode.cfg')) as f:
        cp = configparser.ConfigParser()
        cp.read_file(f)
    hostkey, meetingkey = cp.get('defaults', 'host'), cp.get('defaults', 'meeting')
    parser = argparse.ArgumentParser(description='Generate an attendnace code')
    parser.add_argument('--hostkey', default=hostkey, help='Secret host key; default "%(default)s"')
    parser.add_argument('--meetingkey', default=meetingkey, help='Secret meeting; default "%(default)s"')
    parser.add_argument('--date', default=datetime.date.today().isoformat(), help='Date; default %(default)s')
    parser.add_argument('attendee', help='Attendee name')
    ns = parser.parse_args()
    key = ns.hostkey + ns.meetingkey + ns.date + ns.attendee
    sha1 = hashlib.new('sha1')
    sha1.update(key.encode('utf-8'))
    hashish = sha1.digest()
    print(''.join([str(i % 10) for i in list(hashish)[0:6]]))
    sys.exit(0)


if __name__ == '__main__':
    main()
