#!/bin/sh
#
# edrndir - Search EDRN's Directory Service
#

. $HOME/.secrets/passwords.sh

exec /usr/bin/env LDAPTLS_REQCERT=never \
     /usr/bin/ldapsearch \
    -b dc=edrn,dc=jpl,dc=nasa,dc=gov \
    -s one \
    -D uid=skelly,dc=edrn,dc=jpl,dc=nasa,dc=gov \
    -H ldaps://localhost:1636 \
    -w "$edrn_skelly_password" \
    -z 0 \
    -x \
    "$@"
