#!/bin/sh
#
# edrndir - Search EDRN's Directory Service
#

. $HOME/.secrets/passwords.sh

exec /usr/bin/env LDAPTLS_REQCERT=never \
     /usr/bin/ldapsearch \
    -b dc=edrn,dc=jpl,dc=nasa,dc=gov \
    -s one \
    -D uid=kelly,dc=edrn,dc=jpl,dc=nasa,dc=gov \
    -H ldaps://edrn-ds.jpl.nasa.gov \
    -w "$edrn_kelly_password" \
    -x \
    "$@"

# exec /usr/bin/env LDAPTLS_REQCERT=never \
#      /usr/bin/ldapsearch \
#     -b dc=edrn,dc=jpl,dc=nasa,dc=gov \
#     -s one \
#     -D uid=admin,ou=system \
#     -H ldaps://edrn-ds.jpl.nasa.gov \
#     -w "$edrn_ldap_manager_password" \
#     -x \
#     "$@"
