#!/usr/bin/env python
# encoding: utf-8
#
# Create the LDIF string for a given password for use with LDAP
#

import sys, hashlib, base64


def main(argv):
    if len(argv) != 2:
        print('Usage {} PASSWORD'.format(argv[0]), file=sys.stderr)
        return False
    sha1 = hashlib.sha1()
    sha1.update(argv[1])
    s = '{SHA}' + base64.b64encode(sha1.digest())
    print(base64.b64encode(s))
    return True


if __name__ == '__main__':
    sys.exit(0 if main(sys.argv) else -1)
